version: '3'
services:
    broker:
        build: broker
        ports:
            - 8080:8080
    auldfellas:
        build: auldfellas
        ports:
            - 8081:8081
    girlpower:
        build: girlpower
        ports:
            - 8083:8083
    dodgydrivers:
        build: dodgydrivers
        ports:
            - 8082:8082
    